export function fixSpec(report: { spec: any; issues: any[] }) {
    const { spec, issues } = report
  
    issues.forEach(({ path, method, issue }) => {
      const op = spec.paths[path][method]
      if (issue === 'Missing description') {
        op.description = `Autogenerated description for ${method.toUpperCase()} ${path}`
      }
      if (issue === 'Missing operationId') {
        op.operationId = `${method}_${path.replace(/[\/{}]/g, '_')}`
      }
    })
  
    return spec
  }