import { z } from 'zod';
import {
  ScopeSchema,
  AclRuleSchema,
  AclSchema,
  EventReminderSchema,
  CalendarNotificationSchema,
  CalendarNotificationSettingsSchema,
  ConferencePropertiesSchema,
  CalendarListEntrySchema,
  CalendarListSchema,
  CalendarSchema,
  ChannelParamsSchema,
  ChannelSchema,
  ColorDefinitionSchema,
  ColorsSchema,
  EventSchema,
  EventsSchema,
  FreeBusyRequestItemSchema,
  FreeBusyRequestSchema,
  ErrorSchema,
  TimePeriodSchema,
  FreeBusyCalendarSchema,
  FreeBusyResponseSchema,
  SettingSchema,
  SettingsSchema,
} from '../types';

export {
  ScopeSchema,
  AclRuleSchema,
  AclSchema,
  EventReminderSchema,
  CalendarNotificationSchema,
  CalendarNotificationSettingsSchema,
  ConferencePropertiesSchema,
  CalendarListEntrySchema,
  CalendarListSchema,
  CalendarSchema,
  ChannelParamsSchema,
  ChannelSchema,
  ColorDefinitionSchema,
  ColorsSchema,
  EventSchema,
  EventsSchema,
  FreeBusyRequestItemSchema,
  FreeBusyRequestSchema,
  ErrorSchema,
  TimePeriodSchema,
  FreeBusyCalendarSchema,
  FreeBusyResponseSchema,
  SettingSchema,
  SettingsSchema,
};
