service: public-puppeteer-sls-api

package:
  exclude:
    - venv/**
    - src/**
    - node_modules/serverless-offline/**
    - node_modules/@sparticuz/chromium/**
    - node_modules/@microfox/puppeteer-sls/node_modules/@sparticuz/chromium/**
    - node_modules/@types/node/**
    - node_modules/@typescript-eslint/eslint-plugin/**
    - node_modules/@typescript-eslint/parser/**
    - node_modules/eslint/**
    - node_modules/eslint-import-resolver-alias/**
    - node_modules/eslint-plugin-import/**
    - node_modules/serverless/**
    - node_modules/serverless-offline/**
    - node_modules/serverless-plugin-typescript/**
    - node_modules/typescript/**

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, env:ENVIRONMENT, 'dev'}
  environment: ${file(env.json)}
  timeout: 300 # 5 minutes

custom:
  stage: ${env:ENVIRONMENT, 'dev'}
  serverless-offline:
    printOutput: true
    httpPort: 4000
    lambdaPort: 4002
    useChildProcesses: true
    useWorkerThreads: true
    noCookieValidation: true
    allowCache: true
    hideStackTraces: false
    disableCookieValidation: true
    noTimeout: true
    environment: ${file(env.json)}

functions:
  unifiedHandler:
    handler: dist/index.handler
    timeout: 30 # 0.5 minutes
    events:
      - http:
          path: /{functionName}
          method: any
          cors: true
    # layers:
    #   - arn:aws:lambda:us-east-1:035837222000:layer:chromium-x86-135:1

resources:
  Outputs:
    ApiEndpoints:
      Description: 'API Endpoints'
      Value:
        Fn::Join:
          - ''
          - - 'API: https://'
            - Ref: 'ApiGatewayRestApi'
            - '.execute-api.'
            - Ref: 'AWS::Region'
            - "/${env:ENVIRONMENT, 'dev'}"
