// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { PostApiCustomGenerateData, PostApiCustomGenerateResponses, PostApiGenerateData, PostApiGenerateResponses, GetApiGetData, GetApiGetResponses, GetApiGetLimitData, GetApiGetLimitResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Generate Audio - Custom Mode
 * The custom mode enables users to provide additional details about the music, such as music genre, lyrics, and more.2 audio files will be generated for each request, consuming a total of 10 credits.wait_audio can be set to API mode:• By default, it is set to false, which indicates the background mode. It will only return audio task information, and you will need to call the get API to retrieve detailed audio information.• If set to true, it simulates synchronous mode. The API will wait for a maximum of 100s until the audio is generated, and will directly return the audio link and other information. Recommend using in GPTs and other agents.
 */
export const postApiCustomGenerate = <ThrowOnError extends boolean = false>(options?: Options<PostApiCustomGenerateData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostApiCustomGenerateResponses, unknown, ThrowOnError>({
        url: '/api/custom_generate',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Generate audio based on Prompt.
 * It will automatically fill in the lyrics.2 audio files will be generated for each request, consuming a total of 10 credits.wait_audio can be set to API mode:• By default, it is set to false, which indicates the background mode. It will only return audio task information, and you will need to call the get API to retrieve detailed audio information.• If set to true, it simulates synchronous mode. The API will wait for a maximum of 100s until the audio is generated, and will directly return the audio link and other information. Recommend using in GPTs and other agents.
 */
export const postApiGenerate = <ThrowOnError extends boolean = false>(options?: Options<PostApiGenerateData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostApiGenerateResponses, unknown, ThrowOnError>({
        url: '/api/generate',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get audio information
 */
export const getApiGet = <ThrowOnError extends boolean = false>(options: Options<GetApiGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetApiGetResponses, unknown, ThrowOnError>({
        url: '/api/get',
        ...options
    });
};

/**
 * Get quota information.
 */
export const getApiGetLimit = <ThrowOnError extends boolean = false>(options?: Options<GetApiGetLimitData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiGetLimitResponses, unknown, ThrowOnError>({
        url: '/api/get_limit',
        ...options
    });
};