service: public-discord-api

plugins:
  - serverless-plugin-typescript
  - serverless-api-gateway-throttling

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, env:ENVIRONMENT, 'dev'}
  environment: ${file(env.json)}

custom:
  apiGatewayThrottling:
    maxRequestsPerSecond: 50
    maxConcurrentRequests: 20

functions:
  unifiedHandler:
    handler: dist/index.handler
    events:
      - http:
          path: /{functionName}
          method: any
          cors: true

resources:
  Outputs:
    ApiEndpoints:
      Description: 'API Endpoints'
      Value:
        Fn::Join:
          - ''
          - - 'API: https://'
            - Ref: 'ApiGatewayRestApi'
            - '.execute-api.'
            - Ref: 'AWS::Region'
            - "/${env:ENVIRONMENT, 'dev'}"
