import { orchestratorAgent } from '@/lib/agents/orchestrator';
import { tracingMiddleware } from '@/lib/middleware';

// Apply the tracing middleware to all routes in the orchestrator agent.
orchestratorAgent.use('*', tracingMiddleware);

// We will export a POST handler that processes all incoming requests.
export async function POST(request: Request) {
  // Let the orchestrator agent handle the request and generate a response.
  // We pass '/' as the path because the orchestrator's base path is already set.
  // We add an empty 'messages' array to the request to satisfy the router's type.
  const body = await request.json()

  console.log("body", body)

  // Let the AiRouter handle the request and generate a response.
  // We add an empty 'messages' array to the request to satisfy the router's type.
  const response = orchestratorAgent.handle('/', {
    request: {
      ...body,
      messages: []
    }
  });

  // Return the response generated by the agent.
  return response;
} 