name: Update Package List

on:
  push:
    branches:
      - main

jobs:
  update-package-list:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.head_commit.message, 'Merge pull request ') && contains(github.event.head_commit.message, '/changeset-release/')
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: cd scripts && npm i

      - name: Run update package list script
        run: cd scripts && npm run update:package-list

      - name: Clean up  & reset .microfox files
        run: |
          echo '{"requests": []}' > .microfox/packagefox-build.json
          echo "{}" > .microfox/pr-usage.json

      - name: Check for changes
        id: git-check
        run: |
          git add packages-list.json
          git add README.md
          git add .microfox/packagefox-build.json
          git add .microfox/pr-usage.json
          git diff --staged --quiet || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push if changed
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "chore: update package list [skip ci]"
          git push
